### ISSUE TITLE
Minimal Scroll bar

### ISSUE THREAD

**Issue by AkshayChordiya** [turing-tech/MaterialScrollBar#1]
@krimin-killr21 The library is too damn exciting, I'm eager to put it in my app. The current `ScrollBar` style but I can it be improved?
Just the background, the popup is perfect

**Comment by turing-tech** [comment]
I'm sorry, but I didn't quite get what you meant? What background did you mean? How did you want it to be improved?

**Comment by AkshayChordiya** [comment]
The current scrollbar has fat width, making it slim like in Contacts App of
Lollipop.

​Regards
,
​Akshay Chordiya

**Comment by AkshayChordiya** [comment]
@krimin-killr21 
Check this library: https://github.com/danoz73/RecyclerViewFastScroller
It has small background of scroller, like that way would look nice.

**Comment by turing-tech** [comment]
If you like the appearance of that library, you can use it. This library is designed to emulate a very specific style from Android.

**Comment by AkshayChordiya** [comment]
But I like implementation of this library.

​Regards
,
​Akshay Chordiya
