### ISSUE TITLE
setAutoHide bug.

### ISSUE THREAD

**Issue by Tolriq** [turing-tech/MaterialScrollBar#10]
Testing this library and get into a small problem.

I'm using setAutoHide(true) to have the bar auto hiding.

The bug is easy to trigger scroll the list to have the bar showing.

Start dragging the scroller up and down for a more or less long time after a few seconds the scroll bar auto hide while still dragging and scrolling.

It will auto shows again after 1/2 second and will work correctly after that.

**Comment by turing-tech** [comment]
Fixed for upcoming release.
