### ISSUE TITLE
Cannot find version 13.0.0

### ISSUE THREAD

**Issue by marbat87** [turing-tech/MaterialScrollBar#101]
It seems a build issue in jitpack.

Thanks in advance.

![image](https://user-images.githubusercontent.com/8694304/29019579-35e8d12e-7b5f-11e7-9561-179887fa21d9.png)

**Comment by turing-tech** [comment]
Thanks. I'm looking into it.

**Comment by turing-tech** [comment]
Fixed. Pull 13.0.1
