### ISSUE TITLE
Removing items from adapter does not hide scrollbar

### ISSUE THREAD

**Issue by kasual1** [turing-tech/MaterialScrollBar#105]
When I add items to my adapter, the scrollbar starts to appear as soon as there are enough items in the list.  This works perfectly fine, but when I start removing items from this list the scrollbar should disappear as soon as there are too less items. 
Is there a method that I could call when I delete an item, so that it checks if the list is long enough?
(I guess there should be something in there already, because when I change orientation it then detects that the list is too short and hides the scrollbar)

Thanks in advance, greate work :)

**Comment by turing-tech** [comment]
Thanks for the heads-up! I appreciate the help :)
