### ISSUE TITLE
[Feature Request] Correctly trigger OnScrollListener

### ISSUE THREAD

**Issue by Tolriq** [turing-tech/MaterialScrollBar#11]
It seems currently when fastscrolling the library does not trigger the RecyclerView OnScrollListener listeners.

This is problematic when some other things depends on this being called.

It would be nice to include support for that.

Thanks.

**Comment by turing-tech** [comment]
It will trigger the method in the next update, though the dx and dy will always be zero as it doesn't seem like finding the distance would be easy or even possible. I'll keep working on it.

**Comment by Tolriq** [comment]
Hi,

Thanks, currently I use the findfirst/last from manager so not really a problem.
But maybe this will prevent CoordinatorLayout and actionbar auto hide function from working.

Not yet tested as I wanted to have 100% functions with recyclerview before continuing :)

**Comment by Tolriq** [comment]
Just tested new implementation, it missed the calls to onScrollStateChanged also :(

So maybe this is harder to implement than I thought :(
