### ISSUE TITLE
Indicator is shown without visible scrollbar

### ISSUE THREAD

**Issue by cklar** [turing-tech/MaterialScrollBar#111]
I had the case that a list was completely displaying on one screen, means no scrollbar. But when I pressed on the top right of the list the indicator showed up. I would expect that in such case no Indicator is displayed. 
![device-2018-02-05-135027](https://user-images.githubusercontent.com/2140698/35805956-1ff00582-0a7e-11e8-8f5c-55570a290ca9.png)

**Comment by turing-tech** [comment]
Thanks! I'll look at a fix soon.
