### ISSUE TITLE
cannot be cast to com.turingtechnologies.materialscrollbar.INameableAdapter

### ISSUE THREAD

**Issue by Nkurayijahubert** [turing-tech/MaterialScrollBar#114]
Hello,

Am getting this error when I try to load the MainActivity, there is no clear error in Logcat.

What can I do?

**Comment by turing-tech** [comment]
Is this in the sample or in your own app?

**Comment by Nkurayijahubert** [comment]
It's was in my app, but I have resolve it.
The problem was that I have not implemented INameAdapter in my own adapter.
