### ISSUE TITLE
Wrong RecyclerView

### ISSUE THREAD

**Issue by ProDev2** [turing-tech/MaterialScrollBar#119]
When using it in viewpager it finds the wrong recyclerview. It finds a recyclerview that is in another fragment, which has the same id. I fixed this by setting the recyclerview programmatically and not through the layout.

**Comment by turing-tech** [comment]
We've run into this problem before. I'll try and design an approach where it scans nearby elements first and see if that helps.

**Comment by turing-tech** [comment]
Fixed. Try it out and let me know.
