### ISSUE TITLE
Library doesn't respect recyclerview's vertical padding, as well as item's vertical margin

### ISSUE THREAD

**Issue by DarkMinstrel** [turing-tech/MaterialScrollBar#123]
As soon as I add some, scroll thumb position gets calculated wrong.

**Comment by turing-tech** [comment]
Confirmed and reproduced. This issue should be closed by a forthcoming commit today or tomorrow.

**Comment by DarkMinstrel** [comment]
RecyclerView's padding works differently depending on `android:clipToPadding` attribute.
Make sure to cover both variants.
