### ISSUE TITLE
setHandleColour possible collision

### ISSUE THREAD

**Issue by Tolriq** [turing-tech/MaterialScrollBar#13]
A last one for today:)

setHandleColour(int) can lead to unfortunate collision if seeking for a color value that clash with a color resource id.

This is very rare but can happens.

Maybe handle this like other libs :
setHandleColour(int color)
setHandleColourRes(int colorResid) / setColorResId  ?

**Comment by turing-tech** [comment]
Fixed for upcoming release.

**Comment by Tolriq** [comment]
Thanks, and good job with the library seems to works well and efficient support ;)
