### ISSUE TITLE
Support for GridLayoutManager

### ISSUE THREAD

**Issue by Tolriq** [turing-tech/MaterialScrollBar#14]
Me again :)

Seems currently the lib does not support GridLayoutManager.

Is there plan to support those ?

Would you accept PR if not ?

**Comment by Swisyn** [comment]
Same as me, today i've tried the library on gridlayoutmanager but as you said that it's not working :)

**Comment by Tolriq** [comment]
I've made a fork https://github.com/Tolriq/MaterialScrollBar/commits/master with basic support for that.

I'll see to make PRs but it's far from perfect and I've dropped nineolds so needs special handling.

**Comment by AkshayChordiya** [comment]
@Tolriq @Swisyn The library seems to work now with `GridLayoutManager`.
@krimin-killr21 I think you can close this issue

**Comment by AkshayChordiya** [comment]
@krimin-killr21 
Unfortunately this bug is not fixed. It works with `GridLayoutManager` but the alphabets shown in the bubble are wrong. I hope you re-open this issue and look into it. Thanks

**Comment by turing-tech** [comment]
@Akshay I'll look into it on Monday. Thanks for the heads-up.
