### ISSUE TITLE
Using with view in layout

### ISSUE THREAD

**Issue by AkshayChordiya** [turing-tech/MaterialScrollBar#15]
Hi @krimin-killr21 

Currently we can directly use `MaterialScrollBar` directly from Java. But it takes the flexibility, so can you create a some view like `com.packagename.MaterialScrollBar` which would be really cool & flexible to move in layout hierarchy.
Let me know what you think about it.

**Comment by Rainer-Lang** [comment]
@AkshayChordiya Do you mean directly in xml-layout files? Look at new version 8. Maybe this issue could be closed.
