### ISSUE TITLE
Bubble distance from bar

### ISSUE THREAD

**Issue by marbat87** [turing-tech/MaterialScrollBar#17]
Hi,

I think that the bubble is too close to the scrolling bar. There should be a little space between them, if possibile.

See example below from google launcher:
![screenshot 15_ott_2015 10_41_17 am](https://cloud.githubusercontent.com/assets/8694304/10509044/f09d0074-732a-11e5-9f98-7c68ea564a09.png)

**Comment by marbat87** [comment]
Hi @krimin-killr21 

Any news on this project?

Regards,
Marcello

**Comment by turing-tech** [comment]
Sorry, I'm really busy applying to uni at the moment. I'll add a feature for this when I have more time :/
