### ISSUE TITLE
Trying to make it like in Google Now Launcher

### ISSUE THREAD

**Issue by AkshayChordiya** [turing-tech/MaterialScrollBar#18]
The latest version of Google Now Launcher has new kind of Scroller, it isn't completely different just a bit smart.
Can you try to make `MaterialScrollBar` like that way?

**Comment by turing-tech** [comment]
What feature exactly do you mean?

**Comment by AkshayChordiya** [comment]
See the screenshots, you'll get it.

![](https://dl2.pushbulletusercontent.com/6zQVX5ZKZYHFiXPhOh6cJHw7cvFoWtYS/Screenshot_20160111-090706.png)

![](https://dl2.pushbulletusercontent.com/FMQNLRgSTeN6TS65lfRKO9dvyfJYK9WQ/Screenshot_20160111-090734.png)

**Comment by turing-tech** [comment]
Did the API changes introduced in 6.0.0 cover that?

**Comment by AkshayChordiya** [comment]
@krimin-killr21 I'm not sure about it

**Comment by turing-tech** [comment]
Oh, I see what you mean. Yeah, I'll see what I can do.

**Comment by AkshayChordiya** [comment]
@krimin-killr21 Thank you so much

**Comment by turing-tech** [comment]
I've gotten 90% of it done. Working on the animation and then I'll do a check over tomorrow before I publish it.

**Comment by AkshayChordiya** [comment]
Sweet! Yay

​Regards
,
​Akshay Chordiya

**Comment by turing-tech** [comment]
Sorry but its going to take a bit longer because I was busier today than I expected. It'll come soon  though.

**Comment by AkshayChordiya** [comment]
@krimin-killr21 Oh no problem take your time.
PS: I just found that Nova Launcher has same kind of Scroller

**Comment by turing-tech** [comment]
Done. Choose the DragScrollBar option and tell me what you think.

**Comment by AkshayChordiya** [comment]
I'll check it today.

Regards,
Akshay Chordiya

**Comment by Rainer-Lang** [comment]
Any news? Nova Launcher Scroller is pretty nice. ;-)

**Comment by turing-tech** [comment]
@Rainer-Lang Have you checked ou the DragScrollBar option?

**Comment by Rainer-Lang** [comment]
@krimin-killr21 Awesome :)
@AkshayChordiya @krimin-killr21 For me this issue could be closed.

**Comment by AkshayChordiya** [comment]
@krimin-killr21 
I didn't get to try it, I feel you should close the issue for now. If I face any problem I'll re-open the issue.Thanks
