### ISSUE TITLE
Not compatible with Super Recycler View

### ISSUE THREAD

**Issue by AkshayChordiya** [turing-tech/MaterialScrollBar#2]
Hi, I used this easy to use library with another library which is `SuperRecyclerView`
https://github.com/Malinskiy/SuperRecyclerView

And the scroll bar doesn't show up, I try all the possible ways to solve it but couldn't

**Comment by turing-tech** [comment]
I will definitely look into that. Would you mind sending me the relevant code from your app so I can check on what the issue might be?

**Comment by AkshayChordiya** [comment]
List view part

```
mCardsList.setAdapter(mSongsListAdapter);
mSongsListAdapter.setOnItemClickListener(AllSongsFragment.this);
MaterialScrollBar materialScrollBar = new MaterialScrollBar(getActivity(), mCardsList.getRecyclerView());
materialScrollBar.setAutoHide(true);
materialScrollBar.setBarColour(getSecondaryColor());
materialScrollBar.setHandleColour(getSecondaryColor());
materialScrollBar.addSectionIndicator(getActivity());
```

Adapter:

```
@Override
    public Character getCharacterForElement(int i) {
        Character first = mSongs.get(i).getSongTitle().charAt(0);
        if(Character.isDigit(first)){
            first = '#';
        }
        return first;
    }
```

**Comment by turing-tech** [comment]
SuperRecyclerView oddly does not extended the normal recyclerView class and so I can't make it work without major revision of the code that would make the library much larger and less efficient.

**Comment by turing-tech** [comment]
As to the problem you're having, I really can't say. Looks like it should work to me. If you wouldn't mind sharing the whole code with me just I can troubleshoot it myself I could try that way, but otherwise there's not much I can do. (If you did send the code to me email it or something since you obviously wouldn't want it totally public)

**Comment by AkshayChordiya** [comment]
@krimin-killr21 
I solved, it was simpler than I thought. The `SuperRecyclerView` has a method name `getRecyclerView()`  to get the attached `RecyclerView` & use with this library.

EDIT: It turned out the app loads but the `Scroller` doesn't

**Comment by turing-tech** [comment]
Will look into possibly fixing.
