### ISSUE TITLE
Version 7.1.0 and Android 2.3.7

### ISSUE THREAD

**Issue by marbat87** [turing-tech/MaterialScrollBar#24]
Hi,

I updated MaterialScrollBar to the lastest and I noticed that it doesn't work properly on Android 2.3.7.

When scrolling, the recyclerview scrolls and the letter inside the bubble changes, but both the scroller and the bubble stuck on the top and don't move.

Version 7.0.0 worked fine.

Regards.
Marcello

**Comment by turing-tech** [comment]
Thank you for reporting the issue. I will look into it right now.

**Comment by turing-tech** [comment]
After some fun git acrobatics I've rolled everything back to 7.0.1 which is tested as working on 2.3.7. I'm going to work on getting it to look nice on those versions now.
