### ISSUE TITLE
FeatureRequest: new type of FastScroller - picture

### ISSUE THREAD

**Issue by Rainer-Lang** [turing-tech/MaterialScrollBar#28]
I have seen such a FastScroller many times. It looks very lightweight - not so "heavy".
Maybe a feature for future version...

![fastscroller](https://cloud.githubusercontent.com/assets/9607880/13050636/ff179c24-d3f4-11e5-8aef-317f0dbaebb2.jpg)

**Comment by turing-tech** [comment]
This library so far has pursued a very specific style of scrollBar, namely, one based on material design inspired by Google's implementations. This library might be more suited to what you're looking for: https://android-arsenal.com/details/1/1472. Including that style of scrollBar would involve a redefinition of the library which, while I won't rule out, wouldn't occur until I'm sure that no other library already covers the same ground.

**Comment by Rainer-Lang** [comment]
Thanks for the link - BUT I really like your one more :)
I only wanted to make a suggestion. I really like your lib.
