### ISSUE TITLE
Scroll with finger...

### ISSUE THREAD

**Issue by Rainer-Lang** [turing-tech/MaterialScrollBar#29]
If I move the bar with finger then I can move it under/behind the navigationbar -> image
![behind](https://cloud.githubusercontent.com/assets/9607880/13112042/7a21528a-d589-11e5-997c-c5863e93cbba.jpg)

**Comment by turing-tech** [comment]
Was this fixed?

**Comment by Rainer-Lang** [comment]
Sorry couldn't test it yet. I will tell you asap.

**Comment by Rainer-Lang** [comment]
@krimin-killr21 
1) initial issue was fixed - moving bar directly with finger
2) if I move the list (RV) not thebar then the bar moves too - and the bar moves behind the navigationbar

**Comment by turing-tech** [comment]
Okay, thanks. I'll check that out this weekend.

**Comment by Rainer-Lang** [comment]
@krimin-killr21 But not in all cases! I couldn't figure out yet when the bug occurs and when not. Sorry.

I will write if I have new information.

**Comment by Rainer-Lang** [comment]
I didn't see the problem anymore. So I'm closing this issue for now.
