### ISSUE TITLE
ViewRootImpl CalledFromWrongThreadException

### ISSUE THREAD

**Issue by JorisBodin** [turing-tech/MaterialScrollBar#31]
Hi,

I randomly got a force close in my application.
![image](https://cloud.githubusercontent.com/assets/2796439/13323389/89e2660e-dbd9-11e5-9102-9ba019f6becc.png)
In my fragment:
        recyclerView.setAdapter(adapter);
        TouchScrollBar touchScrollBar = (TouchScrollBar) view.findViewById(R.id.touch_scroll_bar);
        touchScrollBar.addIndicator(new CustomIndicator(getContext()), true);
(without xml is identically) 

An idea ?

**Comment by turing-tech** [comment]
I'm rewriting a big part of the backend which will hopefully be finished this weekend and which will hopefully take care of that problem. I'll try and do it tonight if possible.

**Comment by JorisBodin** [comment]
I use design:23.2.0

Thanks for your quickly response.

**Comment by turing-tech** [comment]
À l'avenir, si c'est plus facile je parle français :)

**Comment by JorisBodin** [comment]
Ah super, ça sera plus simple.
J'ai testé avec la lib design:23.1.1, pareil (car j'ai eu des glitch avec la 23.2.0).
En attendant la mise à jour de ta lib, je ne set pas l'Indicator.
Sinon j'ai toujours un problème, que j'avais avant janvier (donc la vielle version de ta lib), l'indicator régulièrement ne disparaît pas. Je te redirais après la MAJ ;)
Merci

**Comment by turing-tech** [comment]
J'espere (et je pense) que j'ai decouvert l'erreur. Demain quand j'ai téléchargé la MAJ vers GitHub, si tu la testes et elle marche pas quand même, dis-moi et je vais essayer de la réparer. Mais comme j'ai dit, je crois bien que je l'ai réparée.

Pour l'autre erreur, quelle version d'Android utilises-tu ?

**Comment by JorisBodin** [comment]
Je suis sur un Nexus 5X donc Android 6.0.1

Alors je voulais compilé avec le numéro de version de ta lib, mais ca ne marche qu'avec le "+"
"Failed to resolve: com.turingtechnologies.materialscrollbar:lib:8.1.0"

Et là avec "com.turingtechnologies.materialscrollbar:lib:8.+" j'ai toujours l'erreur:
"ViewRootImpl$CalledFromWrongThreadException" :'(

Par contre plus de problème avec l'indicator, sauf à sa création où il est affiché tout en haut tant qu'on ne scroll pas. C'est normal ?

**Comment by turing-tech** [comment]
Alors j'ai téléchargé hier une nouvelle version vers GitHub mais j'ai découvert qu'il y avait des erreurs dedans (par exemple avec l'indicateur). Change le gradle à "8.0.0" et ça va marcher. Cet après-midi je vais télécharger les correctifs.

**Comment by JorisBodin** [comment]
Toujours le "CalledFromWrongThreadException" :/
Je pourrais tester dans seulement 3 semaines tes prochains correctifs.

**Comment by turing-tech** [comment]
Si tu peux, teste-le et dis-moi si c'est meilleur maintenant.

**Comment by JorisBodin** [comment]
J'ai du mettre:
    compile 'com.turingtechnologies.materialscrollbar:lib:8.+' au lieu de 8.0.0

Je n'ai pas eu de "CalledFromWrongThreadException" :D, mais en rechargeant plusieurs fois mon fragment j'ai eu au bout d'un moment ça:
![image](https://cloud.githubusercontent.com/assets/2796439/13374999/da72eec4-dd94-11e5-8411-b6cfbfcdd060.png)
:(

**Comment by turing-tech** [comment]
Alors, désolé qu'il y a si beaucoup de problèmes :/ C'est frustrant pour moi aussi :P

Est-ce que tu l'ajoutes avec XML ou code ?

**Comment by JorisBodin** [comment]
Pardon de répondre que maintenant.
Alors la bar est créé en XML puis ajouté avec le code:
TouchScrollBar touchScrollBar = (TouchScrollBar) view.findViewById(R.id.touch_scroll_bar);
touchScrollBar.addIndicator(new CustomIndicator(getContext()), true);

**Comment by turing-tech** [comment]
À moi il me semble que tu essais d'ajouter l'indicateur avant que le recyclerView ne soit chargé/attaché à la fenêtre, oui ? Sinon, quand exactement invoques-tu "addIndicator()" ?

**Comment by JorisBodin** [comment]
Je le rajoute dans le onCreateView du fragment.
![image](https://cloud.githubusercontent.com/assets/2796439/13855048/cec9de32-ec6e-11e5-9599-1a1c8e6bf652.png)

**Comment by turing-tech** [comment]
Puis-je voir aussi le onCreate pour l'activité qui contient le fragment ?

**Comment by JorisBodin** [comment]
![image](https://cloud.githubusercontent.com/assets/2796439/13859637/b6430cb0-ec84-11e5-85b5-7054534399b1.png)
![image](https://cloud.githubusercontent.com/assets/2796439/13859645/c4b96384-ec84-11e5-8a60-2c0e7974cada.png)

**Comment by turing-tech** [comment]
J'ai verifié qu'on peut utiliser le ScrollBar avec des fragments. Il n'y a rien d'autre auquel je peux penser qui provoquerait cette erreur. Si tu voudrais, vous pouvez m'envoyer ton projet en privé et je peux le debugger. Désolé que je ne pouvais pas trouver l'erreur...

Mon adresse courriel c'est wynneplaga@gmail.com

**Comment by JorisBodin** [comment]
J'aimerais bien, mais je n'ai pas eu l'autorisation de t'envoyer mon projet :/

**Comment by amingholami2011** [comment]
-----------------------------------------------------------------------------


Home Page :   WWW.MasterEffect.Ir
