### ISSUE TITLE
Directly clicking on the scrollbar should work

### ISSUE THREAD

**Issue by AkshayChordiya** [turing-tech/MaterialScrollBar#32]
We should be able to directly click on the scrollbar, I mean at any position apart from handle and on clicking that position the `ListView` or RecyclerView` should jump to that position.

It's the default behavior of a `FastScroll` in Android and I think it's missing in this library.

PS: The library is getting too awesome.

**Comment by turing-tech** [comment]
This isn't the behaviour of the Google launcher. I'll consider adding an option to allow user to alter the behaviour when I have some time.

**Comment by AkshayChordiya** [comment]
@krimin-killr21 Your right that it isn't default behaviour of Google Launcher. But it is behaviour of `FastScroller` since the beginning. I don't know why it has gone now.
Adding an option for it would be highly appreciated.

**Comment by AkshayChordiya** [comment]
@krimin-killr21 You haven't released the new update `9.0.0`. Hence the library is not available to download. Waiting for you too release.

**Comment by AkshayChordiya** [comment]
@krimin-killr21 
Got the new version. It works like a charm.
