### ISSUE TITLE
Need larger bubble and more spacing

### ISSUE THREAD

**Issue by AkshayChordiya** [turing-tech/MaterialScrollBar#34]
I have been using this library since a while and I have found this issue which is extremely minor but really effective issue. I found this issue when I was scrolling through list where the bubble obstructed the view and was difficult to read the alphabet in the bubble.

Here's the solution which I think: 
1. Increasing the size of bubble
2. Increasing the space between bubble and the handle
   Increase the space when setting `addSpace` to `true`
   
   `addIndicator({{Indicator}}, {{addSpace}});`

**Comment by turing-tech** [comment]
Could you take a screenshot so I can see what you're talking about?

**Comment by AkshayChordiya** [comment]
I can't that's because the bubble 🗯 of the scroller is blocked by my thumb or any finger I used to scroll. So I suggest a little bigger bubble and bit more spacing between the scroller handle and the bubble.

**Comment by turing-tech** [comment]
I see what you mean. I have a solution I'll work on and see if I can fix it.
