### ISSUE TITLE
Bubble text doesn't display latest values

### ISSUE THREAD

**Issue by davideas** [turing-tech/MaterialScrollBar#35]
Hello, I was evaluating to use this library, but it doesn't display in the Bubble the latest value of RecyclerView when scrolling.
It stops at the first value when fully scrolled down.

**Comment by turing-tech** [comment]
I can add an option to read from first, last, or middle element of the recylerView to fix that. I'll try and get it done today or tomorrow.

**Comment by davideas** [comment]
@krimin-killr21, no hurry for that, but I think the Bubble should display the first elements, and when RecyclerView can't scroll anymore it should display the middle and last elements to cover the last deltaY.

**Comment by turing-tech** [comment]
The problem is I would have to really change the scrolling logic to add some extra deltaX at the bottom and I'm not confident that I could do it correctly or easily. I might try, but if you or someone else who's feeling generous could fork it and develop that I would love it :3

**Comment by davideas** [comment]
I'm working on my FlexibleAdapter project and I was wondering to use your FastScroller, it is more versatile.
I already use another FastScroller that scrolls correctly (only linear unfortunately) and it has a simple layout, it is used in conjunction of the Adapter, easy to use. When I will have some time, in next 2 months probably I can look more inside.
