### ISSUE TITLE
Problems with Drawer on the right

### ISSUE THREAD

**Issue by MFlisar** [turing-tech/MaterialScrollBar#36]
When I use a Drawer on the right in combination with the scrollbar on the right, the scrollbar will catch the touch of opening the drawer and interprete it as a touch on the sidebar... Which results in a scroll the the corresponding position in the list...

Any ideas how to solve that?

**Comment by turing-tech** [comment]
Would you want the scrollBar on the left or do they both need to be on the right side?

**Comment by MFlisar** [comment]
I have one drawer on the left and one on the right. I would like the scrollbar to remain on the right side...

**Comment by davideas** [comment]
@MFlisar, in my opinion they are incompatible, you can't have both, the trigger width is very limited. But can you show an app which has both? I wonder how it could work...

**Comment by MFlisar** [comment]
I have an idea for that as well. It would be nice to have the ability to disable the function that lets the scrollbar appear when I touch the edge...

With this setup, I could combine the drawer and the scrollbar. User would have to scroll to show the scrollbar, mostly this is enough I think... At least for this edge case, this would be acceptable...

@davideas I don't know an app, only mine ;-)
