### ISSUE TITLE
Popup + margin 

### ISSUE THREAD

**Issue by MFlisar** [turing-tech/MaterialScrollBar#38]
I have a transparent toolbar and the `RecyclerView` is underneath it (as the scrollbar is as well). To correctly show the scrollbar, the scrollbar gets a margin on top. This works fine. The problem now is, I would like the popup indicator to never be above the top position of the scrollbar.

Example:

The scrollbar is positioned in a container view and has a padding of 50dp. So I want the popup to consider the top of the scrollbar + 50dp as the top of the region that is available for the popup, resulting in a popup that is never drawn partly above this border...

**Comment by turing-tech** [comment]
Just to make sure I understand, the pop-up is displaying over the toolbar when it should be stopping beneath it?

**Comment by MFlisar** [comment]
Correctly...

**Comment by turing-tech** [comment]
Huh? Did you mean that was accurate or what?
