### ISSUE TITLE
Label with more than 1 char

### ISSUE THREAD

**Issue by marbat87** [turing-tech/MaterialScrollBar#4]
It would be great having the possibility to create labels with more than 1 char.
For example, in a index sorted by page, it could be useful to have the number of the page in the label.

I think that as long as getCharacterForElement() return a Character, this is not possibile.

Could you give a look if it's possible to add this feature?

Thanks in advance.
Marcello

**Comment by turing-tech** [comment]
Will absolutely do this. Expect it hopefully today.

**Comment by turing-tech** [comment]
Wasn't able to do it when I'd hoped but I will do it soon, as soon as possible.

**Comment by turing-tech** [comment]
Fixed in upcoming update.
