### ISSUE TITLE
addIndicator and Kotlin

### ISSUE THREAD

**Issue by carmas123** [turing-tech/MaterialScrollBar#46]
Hi, if you try to use MaterialScrollBar with Kotlin and try to call method
addIndicator(indicator, false) or other DragScrollBar methods you got an error:

java.lang.IllegalAccessError: Illegal class access: 'com.example.app.BaseListFragment' attempting to access 'com.turingtechnologies.materialscrollbar.Indicator'

**Comment by Schinizer** [comment]
A workaround is to wrap those calls using a java class.

```
public class MaterialScrollBarHack
{
    // Hack to make widget work
    public static void Helper(Context context, RecyclerView recyclerView)
    {
        DragScrollBar materialScrollBar = new DragScrollBar(context, recyclerView, true);
        materialScrollBar.setHandleColour(ContextCompat.getColor(context, R.color.colorPrimary));
        materialScrollBar.addIndicator(new CustomIndicator(context), true);
    }
}

// Call this in Kotlin
MaterialScrollBarHack.Helper(context, recyclerView)
```
