### ISSUE TITLE
Text in the bubble cut with using setDraggableFromAnywhere(true)

### ISSUE THREAD

**Issue by zoltanf** [turing-tech/MaterialScrollBar#49]
If the user jumps from an index that has a text with lower width (like in alphabet the letter "i") to an index that has a longer text (like "m") then the letter is cut on display. This only happens when the user directly jumps to the position by pressing the scroll bar on a place where the indicator would display the longer text.

Step 1:
![image](https://cloud.githubusercontent.com/assets/1464667/15182658/03392aac-178e-11e6-8d41-d02547059ac2.png)

Step 2 (jumping directly to letter "M"):
![image](https://cloud.githubusercontent.com/assets/1464667/15182693/2c6bb20a-178e-11e6-8854-e6155c80287c.png)

This was reproduced on an Android 4.1.1 device, ATM I don't know if it applies to other Android versions or not.

Please let me know if you need any further details. Thank you for you for this library.

**Comment by turing-tech** [comment]
Thanks for notifying me about this issue. I will try and fix it as soon as possible.
