### ISSUE TITLE
setHandleColor

### ISSUE THREAD

**Issue by marbat87** [turing-tech/MaterialScrollBar#5]
Hi,

Great update, it workd almost perfectly!!

Just one thing I noticed:
Before the update i was able to use method setHandeColour(int), passing the color itself as parameter.
Now It doesn't work anymore because of the following new line of code in your method, that throws resourceNotFound.. etc...

<pre>
        handleColour = getResources().getColor(colour);
</pre>

Is there a chance to get back also the old implementation?
In my app, for example, I saved the real accentColor integer (choosed by user) in sharedpreferences and it would be very uncomfortable retrieving the resourceId.

Thanks in advance

**Comment by marbat87** [comment]
Ok I found that I can get the hex string from the int color, so I can call:

<pre>
.setHandleColour(String.format("#%06X", 0xFFFFFF & intColor))
</pre>

It seems to be working fine.
I close the issue.

Regards,
Marcello

**Comment by marbat87** [comment]
I think you did a little mess in the new version...

<pre>
public MaterialScrollBar setHandleColour(String colour) {
        this.handleColour = ContextCompat.getColor(this.getContext(), Color.parseColor(colour));
        ((GradientDrawable)this.indicator.getBackground()).setColor(Color.parseColor(colour));
        if(!this.lightOnTouch) {
            ((GradientDrawable)this.indicator.getBackground()).setColor(Color.parseColor(colour));
        }
        return this;
    }
</pre>

You're parsing the hex color and then you use it as a resourceId, exactly at this line:

<pre>
this.handleColour = ContextCompat.getColor(this.getContext(), Color.parseColor(colour));
</pre>

This always throws

<pre>
android.content.res.Resources$NotFoundException: Resource ID #0xff009688
            at android.content.res.Resources.getValue(Resources.java:892)
            at android.content.res.Resources.getColor(Resources.java:622)
            at android.support.v4.content.ContextCompat.getColor(ContextCompat.java:368)
            at com.turingtechnologies.materialscrollbar.MaterialScrollBar.setHandleColour(MaterialScrollBar.java:209)
</pre>

**Comment by marbat87** [comment]
@krimin-killr21  any ETA for fix? :)

**Comment by turing-tech** [comment]
It wasn't necessarily designed around hex colours, more around other string type inputs. I can make a fix that will work for both. It should be quick so either today or tomorrow.

**Comment by marbat87** [comment]
I think that the actual code would return an exception with any input, but maybe I'm wrong.
However thanks for your time.

Regards,
Marcello

**Comment by turing-tech** [comment]
Heh, right you are. I'll still need to get to my computer to make the fix, but that was a simple error in my part. Thanks for the help :)

**Comment by turing-tech** [comment]
Test it out. Should be all fixed now.
