### ISSUE TITLE
MaterialScrollBar doesn't hide

### ISSUE THREAD

**Issue by matteobucci** [turing-tech/MaterialScrollBar#52]
Hi, I have a recyclerview where sometimes I need to show a scrollbar, other times I don't.
The elements on the recyclerview changes at run time, so I would decide when scroolbar should go away and when it should show.
The problem is that I'm not able to do that. I've tried with the method  scrollBar.setScrollBarHidden(false) with a scrollbar added through code, and using scrollBar.setVisibility(GONE) with a scrollbar added trough XML.

**Comment by PtiPingouin** [comment]
Did you find a solution?
