### ISSUE TITLE
How to perform filtering with MaterialScrollBar?

### ISSUE THREAD

**Issue by hanggrian** [turing-tech/MaterialScrollBar#53]
Have someone successfully perform filtering with this library? I have tried to put Filterable implemented in my RecyclerView adapter. However, there is a constant crash when `getFilter().filter()` is triggered: `java.lang.ArrayIndexOutOfBoundsException` is called on `getCharacterForElement()`.

**Comment by Rainer-Lang** [comment]
Try FastAdapter of Mike Penz. It is working great with this lib!
