### ISSUE TITLE
Failed to resolve: appcompat-v7:24.0.0

### ISSUE THREAD

**Issue by simonsmartza** [turing-tech/MaterialScrollBar#54]
My compileSdkVersion has to be 22 or less, due to 3rd party constraints.

This creates the error:
_Error:Failed to resolve: com.android.support:appcompat-v7:24.0.0
Install Repository and sync project_ 

Is there any way around this, an earlier release of your library perhaps?

**Comment by avtarsingh1122** [comment]
If I am using v10.0.3, then I am getting the following error

Error:Failed to resolve: com.android.support:recyclerview-v7:24.0.0
Install Repository and sync project
Open File
Show in Project Structure dialog

Error:Failed to resolve: com.android.support:design:24.0.0
Install Repository and sync project
Open File
Show in Project Structure dialog

If I am using v10.0.2, then I am not getting the above error

**Comment by simonsmartza** [comment]
Thanks av

I tried that, and had to go down to 9.1.0 to get rid of that error, but that opened a whole new can of worms :)

Hopefully the dev can help out here

 _Exception Details com.turingtechnologies.materialscrollbar.CustomExceptions$MissingAttributesException: You are missing the following required attributes from a scroll bar in your XML: [recyclerView, lightOnTouch]_

**Comment by MFlisar** [comment]
Exclude google dependencies like following or similar:

compile('com.krimin-killr21.materialscrollbar ') {
    exclude module: 'support-v4'
}

And then include the version of the support library you want.

This only works of no function that is used in this library has changed its signature

**Comment by simonsmartza** [comment]
Also not working :(
Here is my Gradle (I also tried 10.0.1 & 10.0.0):

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:22.2.1'
    compile 'com.android.support:cardview-v7:22.2.1'
    compile 'com.android.support:recyclerview-v7:22.2.1'
    compile 'com.android.support:design:22.2.1'
    compile 'com.android.support:support-v4:22.2.1'
    compile('com.turingtechnologies.materialscrollbar:lib:10.0.2') {
        exclude module: 'support-v4'
    }
}

Gives:
Error:Failed to resolve: com.android.support:appcompat-v7:23.4.0
Install Repository and sync projec

**Comment by MFlisar** [comment]
Try using following:

exclude module: 'appcompat-v7'

**Comment by MFlisar** [comment]
And afterwards include the app compat version of your choice

**Comment by simonsmartza** [comment]
Still not working, seems to ignore the exclude command
Such a pity
Thanks for your help :)

**Comment by simonsmartza** [comment]
This did the trick!!!: 

compile('com.turingtechnologies.materialscrollbar:lib:10.0.2') {
        exclude module: 'design'
        exclude module: 'unspecified'
    }
