### ISSUE TITLE
[Feature Request] Expose Indicator properties

### ISSUE THREAD

**Issue by thzero** [turing-tech/MaterialScrollBar#59]
Change getIndicatorHeight, getIndicatorWidth, getTextSize to protected properties and the constructor to public so that folks can create new indicators.

**Comment by turing-tech** [comment]
Yeah, I hadn't thought about that as a need, but I'll definitely work on implementing it. I'm on a trip atm but when I get back on about a week I'll refractor the indicator implementation to allow external indicators.

**Comment by thzero** [comment]
No problem... just made some changes locally and sent a pull request.
