### ISSUE TITLE
Indicator bugs

### ISSUE THREAD

**Issue by marbat87** [turing-tech/MaterialScrollBar#6]
Hi,

I found a couple of bugs on the indicator:

1) On API < 21, the indicator color doesn't change, neither setting handle colour (tested on API 17 and 19).
See image below:
![image](https://cloud.githubusercontent.com/assets/8694304/9812826/6ecbcebe-5880-11e5-8f02-83a2c8adf654.png)

2) On API <= 10, the indicator is reverse and it doesn't hide after stop scrolling.
See image below:
![image](https://cloud.githubusercontent.com/assets/8694304/9812868/c8f534ac-5880-11e5-99ad-f574af07ddde.png)

This is my code:

<pre>
new MaterialScrollBar(getActivity(), recyclerView, true)
                .addIndicator(new AlphabetIndicator(getActivity()))
                .setHideDuration(Utility.HIDE_DELAY)
                .setHandleColour(String.format("#%06X", 0xFFFFFF & getThemeUtils().accentColor()))
                .setAutoHide(true);
</pre>

HIDE_DELAY = 1500

**Comment by turing-tech** [comment]
Will fix. I'll add a note when it's fixed. Expect it before Monday, hopefully today.

**Comment by turing-tech** [comment]
Fixed in Version 4.0.1
