### ISSUE TITLE
Using this library with RecyclerView having layout as StaggeredGridLayout

### ISSUE THREAD

**Issue by ankesh4040** [turing-tech/MaterialScrollBar#63]
Developer ,  I really liked your MaterialScrollBar library.  Only issue I have is using this in StaggeredGridLayout.  I am developing a gallery application and in that I use RecyclerView layout manager StaggeredGridLayout.

I Forked your library and tried changing ScrollingUtilities.java file, and was able to use the scrollbar but Scrollbar height and scroll computation is not correctly in sync.

Please help me as to how can I incorporate this library with my project.

Thanks

**Comment by turing-tech** [comment]
You should probably incorporate [ICustomScroller](https://github.com/turing-tech/MaterialScrollBar/blob/master/lib/src/main/java/com/turingtechnologies/materialscrollbar/ICustomScroller.java). For `getDepthForItem()` return the sum of the height of all of the views in the first column from the top to the first visible item. For `getItemIndexForScroll()` follow the instructions. Same for `getTotalDepth()`.

**Comment by ankesh4040** [comment]
> return the sum of the height of all of the views in the first column from the top to the first visible item. 

Is it from the top **to** the first visible item or from the top **of** the frst visible item ?

Also that will  `getDepthForItem` , `getItemIndexForScroll()` and `getTotalDepth()` return same value ??

**Comment by turing-tech** [comment]
From the to of the list, including the elements that are off screen, to the top of the first visible item. And no, they would all return different values.

**Comment by ankesh4040** [comment]
Please as per the image attached tell the value of all three. This would be a great help.

![screenshot-photo-gallery-5eea63177ce849319c2622fbd69b5469](https://cloud.githubusercontent.com/assets/13796819/18051288/21952f44-6e11-11e6-8b61-ed758a3d89f7.jpg)

**Comment by ankesh4040** [comment]
From the name what I understod is :-

a) `getDepthForItem(int index)`   -- > This is height of each row  so I return **x** (height of each item being same)

b) `getItemIndexForScroll(float progress)`   -- > This is that , according to progress where should we scroll to position. So I am return **progress_7_3**  (7 is number of rows  and 3 no. of item in a row)

c) `getTotalDepth()`  -- > This is total height of all rows . So I return **7*x** (7 being no. of rows and x being height of each row)

Please correct me where I am wrong in this.

Thanks

**Comment by turing-tech** [comment]
Assuming that you haven't scrolled down any the values would be:

`getDepthForItem(7 [for example])` = 2x
`getItemIndexForScroll(.5)` = the item halfway down the list
`getTotalDepth()` = x \* the number if visible and nonvisible items.

**Comment by turing-tech** [comment]
Actually that would return those values regardless of scroll.

**Comment by ankesh4040** [comment]
So `getTotalDepth()` is ok

**Comment by ankesh4040** [comment]
Why is this 2x for getDepthForItem(int index)

**Comment by ankesh4040** [comment]
As I have all my items uniform and height of all items is same. So `getDepthForItem(int index)` would always return 2x irrespective of indxe
 ?

**Comment by turing-tech** [comment]
getDepthForItem(int index) returns the depth of the item provided. Because item at index 7 is in the third row, it had two rows above it and therefore is 2 rows down from the top, where a row is x pixles tall.

Suppose I gave item 0, the depth would be zero. If I gave item 3, that would be at depth x, since item 3 is in the second row.

**Comment by ankesh4040** [comment]
ok got it.
 only thing left is `getItemIndexForScroll(float progress)`

**Comment by turing-tech** [comment]
So here it wants the item at the given progress. So if I give .5, I want the index halfway down the list (this means the list of items off screen). Si if there are 100 items which can be presented in the list, assuming they all have the same height, .5 should return item 50. .25 should return item 25, etc.

**Comment by turing-tech** [comment]
Sorry, I should have said: this means the list of items on and off screen.

**Comment by ankesh4040** [comment]
So if there are 153 items  and in a row there are three items then  with progress of 0.5 I should return 76 .

Am I right?

**Comment by turing-tech** [comment]
Yes.

**Comment by ankesh4040** [comment]
Ok, Thanks a lot for help. Will try this in my project
