### ISSUE TITLE
hide scrollBar when list is empty

### ISSUE THREAD

**Issue by pro100svitlo** [turing-tech/MaterialScrollBar#69]
it would be nice if scrollBar would hide if list is empty, cos now it looks weird

**Comment by turing-tech** [comment]
Supposedly this is already implemented. I'll test to see if it's still working when I get the chance.

**Comment by pro100svitlo** [comment]
thanks ;-)
Please, let me know when it will be available

**Comment by turing-tech** [comment]
Sorry for the extreme delay. I've tested and this seems to be working already. If you're still interested will you download the latest version and let me know?
