### ISSUE TITLE
Ability to hide the scroller

### ISSUE THREAD

**Issue by AkshayChordiya** [turing-tech/MaterialScrollBar#7]
Hi @krimin-killr21 

Excellent library. There are couple of situations like Empty list, etc when the scroller is not needed can there be any method for this. I guess I tested `setVisibility()` which didn't work out.

**Comment by turing-tech** [comment]
Fixed. Use setScrollBarHidden(true) from now on.

**Comment by AkshayChordiya** [comment]
Thank you so much.

Regards,
Akshay Chordiya
