### ISSUE TITLE
SwipeRefreshLayout's circle disappears on scroll

### ISSUE THREAD

**Issue by PtiPingouin** [turing-tech/MaterialScrollBar#72]
I have:

```
SwipeRefreshLayout {
    RelativeLayout {
        RecyclerView
    }
}
```

I'm creating the scrollbar programmatically. When I pull / refresh the layout, the refresh indicator appears. Then, as soon as I scroll down, it vanishes.

**Comment by turing-tech** [comment]
Are you scrolling with the bar or the recycelerView?

**Comment by PtiPingouin** [comment]
Both. The problem is in the scroll listener. You're calling this.swipeRefreshLayout.setEnabled(false), which resets the view (and hides it). Check out the implementation of SwipeRefreshLayout.setEnabled()

**Comment by turing-tech** [comment]
I see. Give me a sec to figure out a solution.

**Comment by turing-tech** [comment]
Get the new version 11.2.1 and it should be fixed.

**Comment by PtiPingouin** [comment]
Thanks. I'll give it a try tomorrow.
