### ISSUE TITLE
Support for searchView

### ISSUE THREAD

**Issue by naushad-madakiya** [turing-tech/MaterialScrollBar#79]
I am using `MaterialScrollBar` with `SearchView` after search query I change list and notifyDataSetChange on adapter but ScrollBar doesn't update with new values of List.

**Comment by turing-tech** [comment]
What behaviour suggests that the `MaterialScrollBar` hasn't updated? Is the indicator showing the wrong thing or is the scrolling to not properly matched to the number and location of elements?

**Comment by naushad-madakiya** [comment]
@turing-tech Yes, `MaterialScrollBar` Is not showing proper bubble as per the list items. Also It should be hide/invisible if there are less item to show in Screen.

**Comment by turing-tech** [comment]
I'll need the code for your adapter to debug the issue.
