### ISSUE TITLE
Use of Generics in Adapter

### ISSUE THREAD

**Issue by AkshayChordiya** [turing-tech/MaterialScrollBar#8]
Hi, This library is getting extremely better.
I feel instead of getting `int` using `INameableAdapter` you can make it generic that means we will get `T`in the method.

Moreover I get `-1` causing `ArrayIndexOutOfBoundException`.

This is not an important issue but will make the library more better, I'll try to have a pull request for generics

**Comment by turing-tech** [comment]
What's the benefit if a generic in this context?

**Comment by AkshayChordiya** [comment]
We directly get the object instead of integer, it's not a big issue.
The generic seem more of a design pattern, well that's what I feel.
Though the library is extremely well.

Regards,
Akshay Chordiya

**Comment by turing-tech** [comment]
I considered that, but the problem is ease of use. A novice programmer can grasp an adapter and an index, but it's much more confusing just giving them the object and hoping they'll cast it to whatever the adapter holds.

**Comment by AkshayChordiya** [comment]
Well that's true for novice developer

​Regards
,
​Akshay Chordiya
