### ISSUE TITLE
Improvement - handle empty RecyclerView Adapter

### ISSUE THREAD

**Issue by MFlisar** [turing-tech/MaterialScrollBar#81]
If the adapter is not set, the ScrollingUtilities will crash...

I would suggest adding following before this line https://github.com/turing-tech/MaterialScrollBar/blob/master/lib/src/main/java/com/turingtechnologies/materialscrollbar/ScrollingUtilities.java#L146

    if  (materialScrollBar.recyclerView.getAdapter() == null) {
        return;
    }

In some cases, the adapter may be set lazily... Problem can be solved by setting an empty adapter, but handling this case automatically is probably the better thing to do

**Comment by turing-tech** [comment]
I'll check into that later today. Looks good though.

**Comment by turing-tech** [comment]
I'll check into that later today. Looks good though.
