### ISSUE TITLE
msb_barThickness is not Integer

### ISSUE THREAD

**Issue by arshad115** [turing-tech/MaterialScrollBar#86]
In the library it is defined as a dimension.
`<attr name="msb_barThickness" format="dimension|reference"/>`

**Comment by turing-tech** [comment]
This is correct, no? The thickness sold be given in pixels.

**Comment by khalid-mahmood** [comment]
@turing-tech not working.. app:msb_barThickness="12dp" 
working example please

**Comment by arshad115** [comment]
No, It gives an error when you enter a value in dp, Also the wiki says its an integer.
