### ISSUE TITLE
setHandleColour not working properly

### ISSUE THREAD

**Issue by MFlisar** [turing-tech/MaterialScrollBar#94]
Overwriting the color defined in xml directly after inflating the layout like following does not work:

    scrollBar.setHandleColour(customColor);

Seems like it is somehow later overwritten again... Posting the `setHandleColour` to the view works though but I think the scrollbar should respect the custom color no matter when it is set.

I've not fully checked it but it may be overwritten in the `setUpHandle` function...

**Comment by turing-tech** [comment]
I'll take a look right now.

**Comment by turing-tech** [comment]
Should now be fixed.
